# Generated by Django 5.1.3 on 2024-12-01 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Picture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uploaded_picture', models.ImageField(upload_to='picture/uploaded/')),
                ('enhanced_picture', models.ImageField(blank=True, null=True, upload_to='picture/enhanced/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
